from .Util import *

LANGUAGE = 'en'

translations = {
    'en': {
        '1Settings': "Settings                      ",
        '2ToolInfo': "Tool Info                     ",
        '3ToolWebsites': "Tool Websites                 ",
        '4WebsiteInfoScanner': "Website Info Scanner          ",
        '5WebsiteURLScanner': "Wbesite URL Scanner           ",
        '6URLChecker': "URL Checker                   ",
    	'7SearchInDataBase': "Search In DataBase            ",
    	'8GetYourIp': "Get Your Ip                   ",
    	'9IpInfo': "Ip Info                       ",
    	'10IpPortScanner': "Ip Port Scanner               ",
    	'11IpPinger': "Ip Pinger                     ",
	    '12IpGenerator': "Ip Generator                  ",
	    '13IpScanner': "Ip Scanner                    ",
 	    '14Obfuscator': "Obfuscator                    ",
    	'15VirusBuilder': "Virus Builder                 ",
    	'16RATBuilder': "RAT Builder                   ",
    	'17SqlVulnerability': "Sql Vulnerability             ",
    	'18PhishingAttack': "Phishing Attack               ",
    	'19DoxCreate': "Dox Create                    ",
    	'20DoxTrackerOsint': "Dox Tracker (Osint)           ",
    	'21UsernameTracker': "Username Tracker              ",
    	'22EmailTracker': "Email Tracker                 ",
    	'23EmailInfo': "Email Info                    ",
    	'24NumberInfo': "Number Info                   ",
    	'25PasswordEncrypted': "Password Encrypted            ",
    	'26PasswordDecrypted': "Password Decrypted            ",
    	'27PasswordChecker': "Password Checker              ",
    	'28PasswordGenerator': "Password Generator            ",
    	'29PasswordGeneratorRandom': "Password Generator (Random)   ",
    	'30ArchiveCracker': "Archive Cracker               ",
    	'31SMBCracker': "SMB Cracker                   ",
    	'32DiscordTokenInfo': "Discord Token Info            ",
   		'33DiscordTokenNuker': "Discord Token Nuker           ",
    	'34DiscordTokenJoiner': "Discord Token Joiner          ",
    	'35DiscordTokenLeaver': "Discord Token Leaver          ",
    	'36DiscordTokenLogin': "Discord Token Login           ",
    	'37DiscordTokenToIdAndBrute': "Discord Token To Id And Brute ",
    	'38DiscordTokenServerRaid': "Discord Token Server Raid     ",
    	'39DiscordTokenSpammer': "Discord Token Spammer         ",
    	'40DiscordTokenDeleteFriends': "Discord Token Delete Friends  ",
    	'41DiscordTokenBlockFriends': "Discord Token Block Friends   ",
    	'42DiscordTokenMassDm': "Discord Token Mass Dm         ",
    	'43DiscordTokenDeleteDm': "Discord Token Delete Dm       ",
    	'44DiscordTokenStatusChanger': "Discord Token Status Changer  ",
    	'45DiscordTokenLanguageChanger': "Discord Token Language Changer",
    	'46DiscordTokenHouseChanger': "Discord Token House Changer   ",
    	'47DiscordTokenThemeChanger': "Discord Token Theme Changer   ",
    	'48DiscordTokenGenerator': "Discord Token Generator       ",
    	'49DiscordBotServerBackup': "Discord Bot Server Backup     ",
    	'50DiscordBotServerNuker': "Discord Bot Server Nuker      ",
    	'51DiscordBotServerInvite': "Discord Bot Server Invite     ",
    	'52DiscordBotIdToInvite': "Discord Bot Id to Invite      ",
    	'53DiscordServerInfo': "Discord Server Info           ",
    	'54DiscordNitroGenerator': "Discord Nitro Generator       ",
    	'55DiscordWebhookInfo': "Discord Webhook Info          ",
    	'56DiscordWebhookDelete': "Discord Webhook Delete        ",
    	'57DiscordWebhookSpammer': "Discord Webhook Spammer       ",
    	'58DiscordWebhookGenerator': "Discord Webhook Generator     ",
    	'59DiscordIdToTokenFirstPart': "Discord Id to Token First Part",
    	'60DiscordGrabAnalyze': "Discord Grab Analyze          ",
    	'61RobloxCookieLogin': "Roblox Cookie Login           ",
    	'62RobloxCookieInfo': "Roblox Cookie Info            ",
    	'63RobloxUserInfo': "Roblox User Info              ",
    	'64RobloxIdInfo': "Roblox Id Info                ",
    	'65RobloxRobuxGenerator': "Roblox Robux Generator        ",
    	'66FileEncryptor': "File Encryptor                ",
    	'67FileDecryptor': "File Decryptor                ",
    	'68FileConverter': "File Converter                ",
		'69FileScanner': "File Scanner                  ",
    	'70FacebookDownloader': "Facebook Downloader           ",
    	'71YoutubeDownloader': "Youtube Downloader            ",
    	'72TikTokDownloader': "TikTok Downloader             ",
    	'73SiteDownloader': "Site Downloader               ",
    	'74DarkWebLinks': "Dark Web Links                ",
    	'75Steganography': "Steganography                 ",
    	'76Metadata': "Metadata                      ",
    	'77Spoofer': "Spoofer                       ",
    	'78WinrarPremium': "Winrar Premium                ",
        '79TiktokViews': "Tiktok Views Generator        ",
        'Soon': "Soon                          ",
        'title': "Discord Token Login",
        'input_browser': "Browser -> ",
        'starting': "{} Starting..",
        'ready': "{} Ready!",
        'error_driver': "{} not installed or driver not up to date.",
        'token_connection': "Token Connection..",
        'connected_token': "Connected Token!",
        'leave_tool_warning': "If you leave Titan, the navigator will close!",
	'tool_infos_recovery': "Information Recovery..",
	'Name_Tool': "Name Tool  ",
	'Coding': "Coding  ",
	'Language': "Language  ",
	'Creator': "Creator  ",
	'Platform': "Platform  ",
	'Web_Site': "Website",
	'Discord_Acces': "Access to the Discord server",
	'Site_Acces': "Access to the site",
	'Website_url': "Website Url",
	'Scan': "Scanning..",
	'Domain': "Domain",
	'Secure': "Secure",
	'Open_Ports': "Open Port",
	'Only': "Only",
	'All_Website': "All Website",
	'Choice': "Choice",
	'URL_to_check': "Enter a URL to check",
	'No_found_for_url': "No results found for this URL",
	'Malicious_URL': "scanners detected this URL as malicious",
	'Error_file_not_found': "Error : The file {secondary}2-Input/FileCheck/apikey.txt{primary} could not be found",
	'Continue': "Press to continue",
	'Error': "Error:",
	'ErrorChoiceStart': "Invalid Choice !",
	'ErrorChoice': "Invalid Choice !",
	'ErrorId': "Invalid ID !",
	'ErrorUrl': "Invalid URL !",
	'ErrorResponse': "Invalid Response !",
	'ErrorEdge': "Edge not installed or driver not up to date !",
	'ErrorToken': "Invalid Token !",
	'ErrorNumber': "Invalid Number !",
	'ErrorWebhook': "Invalid Webhook !",
	'ErrorCookie': "Invalid Cookie !",
	'ErrorUsername': "Invalid Username !",
	'ErrorModule': "Error Module (Restart Setup.bat):",
	'OnlyWindows': "This function is only available on Windows 10/11 !",
	'OnlyLinux': "This function is only available on Linux !",
	'TokenNumber': "Token Number",
	'NoToken1': "No Token Discord in file:",
	'NoToken2': "Please add tokens to the file.",
	'User': "User",
	'TokenFound': "Token Discord found",
	'NoDB': "If you don't have a DataBase you can get one on the Discord Server",
	'AddDB1': "Add DataBase to the",
	'AddDB2': "folder.",
	'DBSearch': "Search in DataBase..",
	'Search': "Search",
	'ErrorReadFile': "Error reading file",
	'ErrorSearch': "Error during search:",
	'TotalSearchFile': "Total files searched:",
	'NoResultSearch': "No result found for",
	'IpSearch': "Search your Ip..",
	'PCUsername': "Pc Username    ",
	'PCHostname': "Pc Hostname  ",
	'PCDisplayName': "Pc DisplayName  ",
	'IpPublic': "Ip Public [ipv4]  ",
	'Iplocal': "Ip Local  [ipv4]  ",
	'Ipv6': "Ipv6",
	'Country': "Country   ",
	'City': "City  ",
	'WebhookYN': "Webhook ? (y/n)",
	'ThreadsNumber': "Threads Number",
	'SSLCertifOn': "SSL Certificate:",
	'SSLCertifOff': "SSL Certificate Check Failed:",
	'Protocol': "Protocol",
	'PathToObf': "Path of the file to obfuscate",
	'ObfSucces': "File successfully obfuscated in:",
    'ObfY' : "Do you want to obfuscate the file? (y/n)",
	'TokenBot': "Your Bot Token",
	'ChannelIDRAT': "Your channel ID",
    'RatSucces': "Rat successfully registred in",
	'FileName': "File Name",
	'VulnerabilityScan': "Looking for a vulnerability..",
	'SQLVuln': "Vulnerability SQL:",
	'ErrorFound': "Error Found:",
	'PhishingSucces': "Phishing attack successful. The file is located in the folder",
	'HTMLRecovery': "Html recovery..",
	'JSRecovery': "Javascript recovery..",
	'CssRecovery': "Css recovery..",
	'ErrorCss': "Error retrieving css.",
	'ErrorJS': "Error retrieving JavaScript.",
	'DoxBy': "Doxed By",
	'Reason': "Raison",
	'1Pseudo': "First Pseudo",
	'DiscInfo': "Discord Information:",
	'TokenYN': "Token ? (y/n)",
	'Username': "Username         ",
	'DisplayName': "Display Name",
	'Created': "Created At",
	'Phone': "Phone",
	'Friends': "Friends",
	'GiftDisc': "Gift Code",
	'ErrorEncryptFile': "Error saving encrypted file content:",
	'SaveFileEncrypt': "Encrypted file content saved to",
	'PathFileEncrypt': "Path to file to Encrypt",
	'PasswdCrypt': "Password for Encryption",
	'CryptMethod': "Encryption Method",
	'LanguageChangeFrench': "Language has been changed to French.",
	'LanguageChangeEnglish': "Language has been changed to English.",
	'AccountSearch': "Account search..",
	'Found': "Found:",
	'LaunchAdmin': "Launching the order as administrator...",
	'WinPremium': "Would you like to activate winrar premium? (y/n):",
	'WinActive': "Winrar activated successfully",
	'ErrorWinActive': "Error during activation",
	'CancelOp': "Operation cancelled.",
	'DownloadDone': "Download done!",
	'URLVideo': "URL of the video",
	'ErrorDownloadVideo': "Error to download the video",
	'DownloadDoneFile': "Download done in file",
	'DirectoryCreated': "Directory created:",
	'EnterUsername': "Enter Username",
	'EnterPassList': "Enter Password List",
	'EnterIPAdress': "Enter IP Address",
	'PasswdNoFound': "Password not Found :(",
	'PasswdFound': "Password Found!",
	'ATTEMPT': "ATTEMPT",
	'1SiteDownload': "The site",
	'2SiteDownload': "was successfully downloaded in",
	'ErrorDownloadSite': "Error downloading the site:",
	'ErrorURL': "Please enter a valid URL.",
	'7ZipNotHere': "7-Zip not installed!",
	'7Path': "Archive Path",
	'ArchiveNotFound': "Archive not found!",
	'WordlistFound': "No wordlists found in",
	'NumWordlist': "Enter the wordlist number",
	'WordlistNotFound': "Wordlist not Found!",
	'CustomStatus': "Enter Custom Status",
	'Changed': "Changed",
	'Only3.12': "This script doesn't work with Python version lower than 3.12",
	'TypeSearch': "Search Type",
	'DataBreachSearch': "Search email (breaches, pastes, accounts)",
	'NotEmail': "The target isn't an email.",
	'LeakSearch': "Leak Search..",
	'URLWebhook': "Webhook URL",
	'WebhookDelete': "Webhook Deleted.",
	'StatusCycle': "How many statues do you want to cycle (max 4)",
	'DecryptFile': "Decrypt a file (AES)",
	'PathToDecrypt': "Path to file to Decrypt",
	'PasswdForDecrypt': "Password for Decryption",
	'DecryptedContent': "Decrypted file content saved to",
	'ErrorDecrypt': "Error decrypting file content:",
	'VerifBadge': "Verified Badge",
	'Banned': "Banned",
	'ProgramStop': "Program stopped",
	'InvalidNumber': "Please enter a valid number.",
	'InvalidOption': "Invalid Option.",
	'Channel': "Channel",
	'SpamMessage': "Spam Message",
	'ChannelSpamID': "Channel Spam Id",
	'TimeCrackPass': "Estimated time to crack the password",
	'PassEvaluate': "Password to evaluate",
	'PassStrength': "Password Strength",
	'File': "The File",
	'NotExist': "does not exist.",
	'PhoneNumber': "Phone Number",
	'Formatted': "Formatted",
	'Operator': "Operator",
	'InvalidFormat': "Invalid Format",
	'ErrorMetadata': "Error updating metadata:",
	'ViewMetadata': "View a file's metadata",
	'EditMetadata': "Edit a file's metadata",
	'FilePath': "File Path",
	'FiealdModify': "Name of the field to modify",
	'NewValue': "New value for",
	'SuccesUpdate': "successfully updated to",
	'Metadata': "Metadata",
	'Metadatafor': "Metadata for",
	'MessageEncode': "Message successfully encoded in",
	'EncodeMessage': "Encode a message in an image",
	'DecodeMessage': "Decode a message from an image",
	'ImageNotExist': "The image file does not exist.",
	'PathImage': "Source image path",
	'MessageToEncode': "Enter the message to encode",
	'PathEncodedImage': "Path of the encoded image",
	'DecodedMessage': "Decoded message",
	'ConvertionNotSupport': "Conversion not supported for this file type.",
	'FileConvertedSucces': "File converted successfully:",
	'ConvertOptions': "Conversion options available:",
	'NumberRep': "Number of Repetitions",
	'CycleNumber': "Enter the number of cycles",
	'NoFriends': "No friends found",
	'AnalyzeRapport': "Python File Analysis Report:",
	'StartAnalyze': "Do you want to start the analysis? (y/n)",
	'AnalysisCancel': "Analysis canceled by user",
	'OnePartToken': "Part One Token",
    'BannerColor': "Banner Color",
	'Expired': "Expired",
    'FriendsBlock': "Enter the friend to block",
    'FriendsList': "Friends List",
    'Blocked': "Blocked",
    'BlockAll': "Block All Friends",
    'BlockOne': "Block one Friend",
    'NoDm': "No Dm Found",
    'Delete': "Delete",
    'Password': "Password",
    'EncryptMetod': "Encryption Method",
    'EncryptPassword': "Encrypted Password",
    'EncryptedPasswd': "Password to Encrypt",
    'PasswordCrackBrute': "Password cracking by brute force.. (very long depending on the number of characters)",
    'PasswordCharacters': "Password Characters Number Max",
    'Encryption': "The Encryption",
    'NotAccept': "is not Accepted",
    'SavePassEncrypted': "Do you want to save the encrypted password to a file? (yes/no)",
    'ConfirmPasswdSaved': "Encrypted password saved to",
    'FileSizeReached': "File Size Reached",
    'OpenBrowser': "Open the Browser ? (y/n)",
    'OpenURL': "Opening the URL in your Browser.."
    },
    'fr': {
        '1Settings': "Paramètres                    ",
        '2ToolInfo': "Infos du Tool                 ",
        '3ToolWebsites': "Sites du Tool                 ",
        '4WebsiteInfoScanner': "Scanneur d'infos de sites     ",
        '5WebsiteURLScanner': "Scanneur d'URL de sites       ",
        '6URLChecker': "Vérificateur d'URL            ",
    	'7SearchInDataBase': "Rechercher dans la Database   ",
    	'8GetYourIp': "Obtenez votre adresse IP      ",
    	'9IpInfo': "Informations IP               ",
    	'10IpPortScanner': "Scanner de ports IP           ",
    	'11IpPinger': "Ip Pinger                     ",
	    '12IpGenerator': "Générateur d'adresse IP       ",
	    '13IpScanner': "Scanner IP                    ",
 	    '14Obfuscator': "Obfuscateur                   ",
    	'15VirusBuilder': "Créateur de Virus             ",
    	'16RATBuilder': "Créateur de RAT               ",
    	'17SqlVulnerability': "Vulnérabilité SQL             ",
    	'18PhishingAttack': "Attaque de phishing           ",
    	'19DoxCreate': "Créateur de Dox               ",
    	'20DoxTrackerOsint': "Dox Tracker (Osint)           ",
    	'21UsernameTracker': "Traqueur de nom d'utilisateurs",
    	'22EmailTracker': "Traqueur d'Email              ",
    	'23EmailInfo': "Infos d'un Email              ",
    	'24NumberInfo': "Infos d'un numéro de téléphone",
    	'25PasswordEncrypted': "Chiffrement de Mot de Passe   ",
    	'26PasswordDecrypted': "Déchiffrement de Mot de Passe ",
    	'27PasswordChecker': "Vérificateur de mot de passe  ",
    	'28PasswordGenerator': "Gen de Mot de Passe           ",
    	'29PasswordGeneratorRandom': "Gen de Mot de Passe (Random)  ",
    	'30ArchiveCracker': "Cracker d'archive (Zip, RAR..)",
    	'31SMBCracker': "Cracker de SMB                ",
    	'32DiscordTokenInfo': "Discord Token Info            ",
   		'33DiscordTokenNuker': "Discord Token Nuker           ",
    	'34DiscordTokenJoiner': "Discord Token Joiner          ",
    	'35DiscordTokenLeaver': "Discord Token Leaver          ",
    	'36DiscordTokenLogin': "Discord Token Connection      ",
    	'37DiscordTokenToIdAndBrute': "Discord Token à ID et Brute   ",
    	'38DiscordTokenServerRaid': "Discord Token Server Raid     ",
    	'39DiscordTokenSpammer': "Discord Token Spammeur        ",
    	'40DiscordTokenDeleteFriends': "Discord Token Delete Friends  ",
    	'41DiscordTokenBlockFriends': "Discord Token Block Friends   ",
    	'42DiscordTokenMassDm': "Discord Token Mass mp         ",
    	'43DiscordTokenDeleteDm': "Discord Token supprimer mp    ",
    	'44DiscordTokenStatusChanger': "Discord Token Status Changer  ",
    	'45DiscordTokenLanguageChanger': "Discord Token Language Changer",
    	'46DiscordTokenHouseChanger': "Discord Token House Changer   ",
    	'47DiscordTokenThemeChanger': "Discord Token Theme Changer   ",
    	'48DiscordTokenGenerator': "Discord Générateur de Token   ",
    	'49DiscordBotServerBackup': "Discord Bot Server Backup     ",
    	'50DiscordBotServerNuker': "Discord Bot Server Nuker      ",
    	'51DiscordBotServerInvite': "Discord Bot Server Invite     ",
    	'52DiscordBotIdToInvite': "Discord Bot Id à Invitation   ",
    	'53DiscordServerInfo': "Discord Server Info           ",
    	'54DiscordNitroGenerator': "Discord Générateur de Nitro   ",
    	'55DiscordWebhookInfo': "Discord Infos d'un Webhook    ",
    	'56DiscordWebhookDelete': "Discord Supprimeur de Webhook ",
    	'57DiscordWebhookSpammer': "Discord Spammeur de Webhook   ",
    	'58DiscordWebhookGenerator': "Discord Générateur de Webhook ",
    	'59DiscordIdToTokenFirstPart': "Discord Id to Token First Part",
    	'60DiscordGrabAnalyze': "Discord Grab Analyze          ",
    	'61RobloxCookieLogin': "Roblox Cookie Connection      ",
    	'62RobloxCookieInfo': "Roblox Infos de cookies       ",
    	'63RobloxUserInfo': "Roblox Infos d'Utilisateur    ",
    	'64RobloxIdInfo': "Roblox Id Info                ",
    	'65RobloxRobuxGenerator': "Roblox Générateur de Robux    ",
    	'66FileEncryptor': "Chiffreur de Fichiers         ",
    	'67FileDecryptor': "Déchiffreur de Fichiers       ",
    	'68FileConverter': "Convertisseur de Fichiers     ",
		'69FileScanner': "Scanneur de Fichiers          ",
    	'70FacebookDownloader': "Téléchargeur Facebook         ",
    	'71YoutubeDownloader': "Téléchargeur Youtube          ",
    	'72TikTokDownloader': "Téléchargeur Tiktok           ",
    	'73SiteDownloader': "Téléchargeur de Site          ",
    	'74DarkWebLinks': "Sites du Dark Web             ",
    	'75Steganography': "Steganographie                ",
    	'76Metadata': "Métadonnées                   ",
    	'77Spoofer': "Spoofer                       ",
    	'78WinrarPremium': "Winrar Premium                ",
        '79TiktokViews': "Générateur de vues Tiktok                ",
        'Soon': "Bientôt                       ",
        'title': "Connexion Token Discord",
        'input_browser': "Navigateur -> ",
        'starting': "Démarrage de {}...",
        'ready': "{} Prêt !",
        'error_driver': "{} non installé ou pilote non à jour.",
        'token_connection': "Connexion au Token...",
        'connected_token': "Token connecté !",
        'leave_tool_warning': "Si vous quittez Titan, le navigateur se fermera !",
	'tool_infos_recovery': "Récupération des informations..",
	'Name_Tool': "Nom du Tool",
	'Coding': "Code    ",
	'Language': "Langues   ",
	'Creator': "Createur ",
	'Platform': "Platforme ",
	'Web_Site': "Site Web",
	'Discord_Acces': "Accès au serveur Discord",
	'Site_Acces': "Accès au site",
	'Website_url': "Url du Site",
	'Scan': "Scan en cours..",
	'Domain': "Domaine",
	'Secure': "Sécurisé",
	'Open_Ports': "Port ouvert",
	'Only': "Seulement",
	'All_Website': "Tout le Site",
	'Choice': "Votre choix",
	'URL_to_check': "Entrez l'URL à vérifier",
	'No_found_for_url': "Aucun résultat pour cette URL",
	'Malicious_URL': "scanners ont détecté cette URL comme malveillante",
	'Error_file_not_found': "Erreur : le fichier {secondary}2-Input/FileCheck/apikey.txt{primary} n'a pas pu être trouvé",
	'Continue': "Appuyez pour continuer",
	'Error': "Erreur :",
	'ErrorChoiceStart': "Choix Invalide !",
	'ErrorChoice': "Choix Invalide !",
	'ErrorId': "ID Invalide !",
	'ErrorUrl': "URL Invalide !",
	'ErrorResponse': "Réponse Invalide !",
	'ErrorEdge': "Edge non installé ou pilote non à jour !",
	'ErrorToken': "Token Invalide !",
	'ErrorNumber': "Numéro Invalide !",
	'ErrorWebhook': "Webhook Invalide !",
	'ErrorCookie': "Cookie Invalide !",
	'ErrorUsername': "Username Invalide !",
	'ErrorModule': "Erreur de module (redémarrez Setup.bat) :",
	'OnlyWindows': "Cette fonction est uniquement disponible sur Windows 10/11 !",
	'OnlyLinux': "Cette fonction n'est disponible que sous Linux !",
	'TokenNumber': "Numéro du Token",
	'NoToken1': "Aucun Token Discord dans le fichier :",
	'NoToken2': "Veuillez ajouter des Tokens au fichier.",
	'User': "Utilisateur",
	'TokenFound': "Token Discord trouvé",
	'NoDB': "Si vous n'avez pas de Database, vous pouvez en obtenir une sur le serveur Discord",
	'AddDB1': "Ajouter ls Databases ici",
	'DBSearch': "Recherche dans les DataBases..",
	'Search': "Rechercher",
	'ErrorReadFile': "Erreur lors de la lecture du fichier",
	'ErrorSearch': "Erreur lors de la recherche :",
	'TotalSearchFile': "Nombre total de fichiers recherchés :",
	'NoResultSearch': "Aucun résultat trouvé pour",
	'IpSearch': "Recherche de votre adresse IP..",
	'PCUsername': "Nom d'utilisateur PC",
	'PCHostname': "Nom d'hôte du PC  ",
	'PCDisplayName': "Nom d'affichage du PC",
	'IpPublic': "IP publique [ipv4]     ",
	'Iplocal': "Ip Locale  [ipv4]      ",
	'Ipv6': "Ipv6     ",
	'Country': "Pays     ",
	'City': "Ville ",
	'WebhookYN': "Webhook ? (o/n)",
	'ThreadsNumber': "Nombre de Threads",
	'SSLCertifOn': "Certificat SSL :",
	'SSLCertifOff': "Échec de la vérification du certificat SSL :",
	'Protocol': "Protocole ",
	'PathToObf': "Chemin du fichier à obfusquer",
	'ObfSucces': "Fichier obfusqué avec succès dans :",
    'ObfY' : "Voulez-vous obfusquer le fichier ? (o/n)",
	'TokenBot': "Le Token de votre Bot",
	'ChannelIDRAT': "L'ID du salon",
    'RatSucces': "Rat enregistré avec succès dans",
	'FileName': "Nom du Fichier",
	'VulnerabilityScan': "À la recherche d'une vulnérabilité..",
	'SQLVuln': "Vulnérabilité SQL :",
	'ErrorFound': "Erreur détectée :",
	'PhishingSucces': "Attaque de phishing réussie. Le fichier se trouve dans le dossier",
	'HTMLRecovery': "Récupération HTML..",
	'JSRecovery': "Récupération JavaScript..",
	'CssRecovery': "Récupération Css..",
	'ErrorCss': "Erreur lors de la récupération du css.",
	'ErrorJS': "Erreur lors de la récupération du JavaScript.",
	'DoxBy': "Dox par ",
	'Reason': "Raison",
	'1Pseudo': "1er Pseudo  ",
	'DiscInfo': "Informations Discord :",
	'TokenYN': "Token ? (o/n)",
	'Username': "Nom d'Utilisateur",
	'DisplayName': "Nom d'Affichage",
	'Created': "Crée le",
	'Phone': "Téléphone",
	'Friends': "Amis",
	'GiftDisc': "Code cadeau",
	'ErrorEncryptFile': "Erreur lors de l'enregistrement du contenu du fichier chiffré :",
	'SaveFileEncrypt': "Contenu du fichier chiffré enregistré sur",
	'PathFileEncrypt': "Chemin du fichier à Chiffrer",
	'PasswdCrypt': "Mot de passe pour le chiffrement",
	'CryptMethod': "Méthode de Chiffrement",
	'LanguageChangeFrench': "La langue a été changée en français.",
	'LanguageChangeEnglish': "La langue a été changée en Anglais.",
	'AccountSearch': "Recherche de compte..",
	'Found': "Trouvé :",
	'LaunchAdmin': "Lancer la commande en tant qu'administrateur...",
	'WinPremium': "Souhaitez-vous activer Winrar Premium ? (y/n) :",
	'WinActive': "Winrar activé avec succès",
	'ErrorWinActive': "Erreur lors de l'activation",
	'CancelOp': "Opération annulée.",
	'DownloadDone': "Téléchargement terminé !",
	'URLVideo': "URL de la vidéo",
	'ErrorDownloadVideo': "Erreur lors du téléchargement de la vidéo",
	'DownloadDoneFile': "Téléchargement effectué dans le fichier",
	'DirectoryCreated': "Répertoire créé :",
	'EnterUsername': "Entrez le nom d'utilisateur",
	'EnterPassList': "Entrez la liste de mots de passes",
	'EnterIPAdress': "Entrez l'adresse IP",
	'PasswdNoFound': "Mot de passe non trouvé :(",
	'PasswdFound': "Mot de passe Trouvé ! ",
	'ATTEMPT': "ESSAI",
	'1SiteDownload': "Le site",
	'2SiteDownload': "a été téléchargé avec succès dans",
	'ErrorDownloadSite': "Erreur lors du téléchargement du site :",
	'ErrorURL': "Veuillez entrer une URL valide.",
	'7ZipNotHere': "7-Zip n'est pas installé !",
	'7Path': "Chemin de l'archive",
	'ArchiveNotFound': "Archive non trouvée !",
	'WordlistFound': "Aucune wordlist trouvée dans",
	'NumWordlist': "Entrez le numéro de la wordlist",
	'WordlistNotFound': "Wordlist non trouvée !",
	'CustomStatus': "Entrez un Status customisé",
	'Changed': "Changé",
	'Only3.12': "Ce script ne fonctionne pas avec une version Python inférieure à 3.12",
	'TypeSearch': "Type de recherche",
	'DataBreachSearch': "Rechercher des e-mails (breachs, pastes, comptes)",
	'NotEmail': "La cible n'est pas un email.",
	'LeakSearch': "Recherche de leaks..",
	'URLWebhook': "URL du Webhook",
	'WebhookDelete': "Webhook supprimé.",
	'StatusCycle': "Combien de statues voulez-vous en cycle (max 4)",
	'DecryptFile': "Déchiffrer un fichier (AES)",
	'PathToDecrypt': "Chemin du fichier à déchiffrer",
	'PasswdForDecrypt': "Mot de passe pour le déchiffrement",
	'DecryptedContent': "Contenu du fichier décgiffré enregistré dans",
	'ErrorDecrypt': "Erreur lors du déchiffrement du contenu du fichier :",
	'VerifBadge': "Badge Vérifié",
	'Banned': "Bannis",
	'ProgramStop': "Programme Stoppé",
	'InvalidNumber': "Veuillez entrer un numéro valide.",
	'InvalidOption': "Option non valide.",
	'Channel': "Salon",
	'SpamMessage': "Message à Spam",
	'ChannelSpamID': "Id du Salon à Spam",
	'TimeCrackPass': "Temps hestimé a cracker le mot de passe",
	'PassEvaluate': "Mot de Passe à évaluer",
	'PassStrength': "Force du Mot de Passe",
	'File': "Le fichier",
	'NotExist': "n'existe pas.",
	'PhoneNumber': "Numéro de téléphone",
	'Formatted': "Formatté",
	'Operator': "Opérateur",
	'InvalidFormat': "Format Invalide",
	'ErrorMetadata': "Erreur lors de la mise à jour des métadonnées :",
	'ViewMetadata': "Voir les métadonnées d'un fichier",
	'EditMetadata': "Modifier les métadonnées d'un fichier",
	'FilePath': "Chemin du Fichier",
	'FiealdModify': "Nom du champ à modifier",
	'NewValue': "Nouvelle valeur pour",
	'SuccesUpdate': "mise à jour avec succès à",
	'Metadata': "Métadonnée",	
	'Metadatafor': "Métadonnées pour",
	'MessageEncode': "Message encodé avec succès dans",
	'EncodeMessage': "Encoder un message dans une image",
	'DecodeMessage': "Décoder un message d'une image",
	'ImageNotExist': "Le fichier image n'existe pas.",
	'PathImage': "Chemin de l'image source"
	'MessageToEncode' "Entrez le message à encoder",
	'PathEncodedImage': "Chemin de l'image encodée",
	'DecodedMessage': "Message décodé",
	'ConvertionNotSupport': "Conversion non prise en charge pour ce type de fichier.",
	'FileConvertedSucces': "Fichier converti avec succès :",
	'ConvertOptions': "Options de conversion disponibles :",
	'NumberRep': "Nombre de répétitions",
	'CycleNumber': "Entrez le Nombre de Cycles",
	'NoFriends': "Aucun Amis Trouvé",
	'AnalyzeRapport': "Rapport d'analyse des fichiers Python :",
	'StartAnalyze': "Voulez-vous démarrer l'analyse ? (y/n)",
	'AnalysisCancel': "Analyse annulée par l'utilisateur",
	'OnePartToken': "Première Partie du Token",	
    'BannerColor': "Couleur de la bannière",
    'Expired': "Expiré",
    'FriendsBlock': "Entrez l'ami à bloquer",
    'FriendsList': "Liste d'amis",
    'Blocked': "Bloqué",
    'BlockAll': "Bloquer tous les amis",
    'BlockOne': "Bloquer un Seul Amis",
    'NoDm': "Aucun Dm trouvé",
    'Delete': "Supprimé",
    'Password': "Mot de Passe",
    'EncryptMetod': "Métode de Chiffrement",
    'EncryptPassword': "Mot de Passe Chiffré",
    'EncryptedPasswd': "Mot de Passe à Chiffrer",
    'PasswordCrackBrute': "Craquage de mot de passe par force brute.. (très long selon le nombre de caractères)",
    'PasswordCharacters': "Nombre Max de Caractères du Mot de Passe",
    'Encryption': "Le chiffrement",
    'NotAccept': "n'est pas accepté par",
    'SavePassEncrypted': "Voulez-vous enregistrer le mot de passe chiffré dans un fichier ? (o/n)",
    'ConfirmPasswdSaved': "Mot de passe chiffré dans",
    'FileSizeReached': "Taille du fichier atteinte",
    'OpenBrowser': "Ouvrir dans le navigateur ? (o/n)",
    'OpenURL': "Ouverture de l'URL dans votre navigateur.."
    },
    'es': {
    'title': "Conexión Token Discord",
    'input_browser': "Navegador -> ",
    'starting': "Iniciando {}...",
    'ready': "{} ¡Listo!",
    'error_driver': "{} no está instalado o el controlador no está actualizado.",
    'token_connection': "Conectando al Token...",
    'connected_token': "¡Token conectado!",
    'leave_tool_warning': "¡Si sales de Titan, el navegador se cerrará!",
    'tool_infos_recovery': "Recuperando información...",
    'Name_Tool': "Nombre de la Herramienta",
    'Coding': "Código    ",
    'Language': "Idiomas   ",
    'Creator': "Creador ",
    'Platform': "Plataforma ",
    'Web_Site': "Sitio Web",
    'Discord_Acces': "Acceso al servidor de Discord",
    'Site_Acces': "Acceso al sitio",
    'Website_url': "URL del sitio",
    'Scan': "Escaneando...",
    'Domain': "Dominio",
    'Secure': "Seguro",
    'Open_Ports': "Puerto abierto",
    'Only': "Solo",
    'All_Website': "Todo el sitio",
    'Choice': "Tu elección",
    'URL_to_check': "Ingresa la URL para verificar",
    'No_found_for_url': "No se encontraron resultados para esta URL",
    'Malicious_URL': "escáneres detectaron esta URL como maliciosa",
    'Error_file_not_found': "Error: No se pudo encontrar el archivo {secondary}2-Input/FileCheck/apikey.txt{primary}",
    'Continue': "Presiona para continuar",
    'Error': "Error:",
    'ErrorChoiceStart': "¡Opción inválida!",
    'ErrorChoice': "¡Opción inválida!",
    'ErrorId': "¡ID Inválida!",
    'ErrorUrl': "¡URL Inválida!",
    'ErrorResponse': "¡Respuesta inválida!",
    'ErrorEdge': "¡Edge no está instalado o el controlador no está actualizado!",
    'ErrorToken': "¡Token Inválido!",
    'ErrorNumber': "¡Número Inválido!",
    'ErrorWebhook': "¡Webhook Inválido!",
    'ErrorCookie': "¡Cookie Inválida!",
    'ErrorUsername': "¡Nombre de usuario Inválido!",
    'ErrorModule': "Error de módulo (reinicia Setup.bat):",
    'OnlyWindows': "¡Esta función solo está disponible en Windows 10/11!",
    'OnlyLinux': "¡Esta función solo está disponible en Linux!",
    'TokenNumber': "Número de Token",
    'NoToken1': "No hay ningún Token de Discord en el archivo:",
    'NoToken2': "Por favor, añade Tokens al archivo.",
    'User': "Usuario",
    'TokenFound': "Token de Discord encontrado",
    'NoDB': "Si no tienes una base de datos, puedes obtener una en el servidor de Discord",
    'AddDB1': "Añade las bases de datos aquí",
    'DBSearch': "Buscando en las bases de datos...",
    'Search': "Buscar",
    'ErrorReadFile': "Error al leer el archivo",
    'ErrorSearch': "Error en la búsqueda:",
    'TotalSearchFile': "Número total de archivos buscados:",
    'NoResultSearch': "No se encontraron resultados para",
    'IpSearch': "Buscando tu dirección IP...",
    'PCUsername': "Nombre de usuario del PC",
    'PCHostname': "Nombre de host del PC",
    'PCDisplayName': "Nombre de pantalla del PC",
    'IpPublic': "IP pública [ipv4]",
    'Iplocal': "IP local [ipv4]",
    'Ipv6': "Ipv6",
    'Country': "País",
    'City': "Ciudad",
    'WebhookYN': "¿Webhook? (s/n)",
    'ThreadsNumber': "Número de Threads",
    'SSLCertifOn': "Certificado SSL:",
    'SSLCertifOff': "Falló la verificación del certificado SSL:",
    'Protocol': "Protocolo",
    'PathToObf': "Ruta del archivo a ofuscar",
    'ObfSucces': "Archivo ofuscado con éxito en:",
    'ObfY' : "¿Quieres ofuscar el archivo? (y/n)",
    'TokenBot': "El Token de tu Bot",
    'ChannelIDRAT': "El ID del canal",
    'RatSucces': "Rata registrada exitosamente en",
    'FileName': "Nombre del archivo",
    'VulnerabilityScan': "Buscando vulnerabilidades...",
    'SQLVuln': "Vulnerabilidad SQL:",
    'ErrorFound': "Error detectado:",
    'PhishingSucces': "Ataque de phishing exitoso. El archivo se encuentra en la carpeta",
    'HTMLRecovery': "Recuperando HTML...",
    'JSRecovery': "Recuperando JavaScript...",
    'CssRecovery': "Recuperando CSS...",
    'ErrorCss': "Error al recuperar el CSS.",
    'ErrorJS': "Error al recuperar el JavaScript.",
    'DoxBy': "Dox por ",
    'Reason': "Razón",
    '1Pseudo': "1er Pseudo",
    'DiscInfo': "Información de Discord:",
    'TokenYN': "¿Token? (s/n)",
    'Username': "Nombre de usuario",
    'DisplayName': "Nombre de pantalla",
    'Created': "Creado el",
    'Phone': "Teléfono",
    'Friends': "Amigos",
    'GiftDisc': "Código de regalo",
    'ErrorEncryptFile': "Error al guardar el contenido del archivo cifrado:",
    'SaveFileEncrypt': "Contenido del archivo cifrado guardado en",
    'PathFileEncrypt': "Ruta del archivo a cifrar",
    'PasswdCrypt': "Contraseña para el cifrado",
    'CryptMethod': "Método de cifrado",
    'LanguageChangeFrench': "El idioma ha sido cambiado a francés.",
    'LanguageChangeEnglish': "El idioma ha sido cambiado a inglés.",
    'AccountSearch': "Buscando cuenta...",
    'Found': "Encontrado:",
    'LaunchAdmin': "Ejecutando el comando como administrador...",
    'WinPremium': "¿Deseas activar Winrar Premium? (s/n):",
    'WinActive': "Winrar activado con éxito",
    'ErrorWinActive': "Error al activar",
    'CancelOp': "Operación cancelada.",
    'DownloadDone': "¡Descarga completada!",
    'URLVideo': "URL del video",
    'ErrorDownloadVideo': "Error al descargar el video",
    'DownloadDoneFile': "Descarga completada en el archivo",
    'DirectoryCreated': "Directorio creado:",
    'EnterUsername': "Introduce el nombre de usuario",
    'EnterPassList': "Introduce la lista de contraseñas",
    'EnterIPAdress': "Introduce la dirección IP",
    'PasswdNoFound': "Contraseña no encontrada :(",
    'PasswdFound': "¡Contraseña encontrada!",
    'ATTEMPT': "INTENTO",
    '1SiteDownload': "El sitio",
    '2SiteDownload': "ha sido descargado exitosamente en",
    'ErrorDownloadSite': "Error al descargar el sitio:",
    'ErrorURL': "Por favor, introduce una URL válida.",
    '7ZipNotHere': "¡7-Zip no está instalado!",
    '7Path': "Ruta del archivo",
    'ArchiveNotFound': "¡Archivo no encontrado!",
    'WordlistFound': "No se encontró ninguna wordlist en",
    'NumWordlist': "Introduce el número de la wordlist",
    'WordlistNotFound': "¡Wordlist no encontrada!",
    'CustomStatus': "Introduce un estado personalizado",
    'Changed': "Cambiado",
    'Only3.12': "Este script no funciona con una versión de Python inferior a 3.12",
    'TypeSearch': "Tipo de búsqueda",
    'DataBreachSearch': "Buscar correos electrónicos (brechas, pastes, cuentas)",
    'NotEmail': "El objetivo no es un correo electrónico.",
    'LeakSearch': "Buscando fugas...",
    'URLWebhook': "URL del Webhook",
    'WebhookDelete': "Webhook eliminado.",
    'StatusCycle': "¿Cuántos estados quieres en ciclo (máximo 4)?",
    'DecryptFile': "Descifrar un archivo (AES)",
    'PathToDecrypt': "Ruta del archivo a descifrar",
    'PasswdForDecrypt': "Contraseña para descifrar",
    'DecryptedContent': "Contenido del archivo descifrado guardado en",
    'ErrorDecrypt': "Error al descifrar el contenido del archivo:",
    'VerifBadge': "Insignia Verificada",
    'Banned': "Prohibido",
    'ProgramStop': "Programa detenido",
    'InvalidNumber': "Por favor, introduce un número válido.",
    'InvalidOption': "Opción no válida.",
    'Channel': "Canal",
    'SpamMessage': "Mensaje de spam",
    'ChannelSpamID': "ID del canal para spam",
    'TimeCrackPass': "Tiempo estimado para romper la contraseña",
    'PassEvaluate': "Contraseña a evaluar",
    'PassStrength': "Fortaleza de la contraseña",
    'File': "El archivo",
    'NotExist': "no existe.",
    'PhoneNumber': "Número de teléfono",
    'Formatted': "Formateado",
    'Operator': "Operador",
    'InvalidFormat': "Formato inválido",
    'ErrorMetadata': "Error al actualizar los metadatos:",
    'ViewMetadata': "Ver los metadatos de un archivo",
    'EditMetadata': "Editar los metadatos de un archivo",
    'FilePath': "Ruta del archivo",
    'FiealdModify': "Nombre del campo a modificar",
    'NewValue': "Nuevo valor para",
    'SuccesUpdate': "actualizado con éxito a",
    'Metadata': "Metadato",
    'Metadatafor': "Metadatos para",
    'MessageEncode': "Mensaje codificado con éxito en",
    'EncodeMessage': "Codificar un mensaje en una imagen",
    'DecodeMessage': "Decodificar un mensaje de una imagen",
    'ImageNotExist': "El archivo de imagen no existe.",
    'PathImage': "Ruta de la imagen de origen",
    'MessageToEncode': "Introduce el mensaje a codificar",
    'PathEncodedImage': "Ruta de la imagen codificada",
    'DecodedMessage': "Mensaje decodificado",
    'ConvertionNotSupport': "Conversión no compatible para este tipo de archivo.",
    'FileConvertedSucces': "Archivo convertido con éxito:",
    'ConvertOptions': "Opciones de conversión disponibles:",
    'NumberRep': "Número de repeticiones",
    'CycleNumber': "Introduce el número de ciclos",
    'NoFriends': "No se encontraron amigos",
    'AnalyzeRapport': "Informe de análisis de archivos Python:",
    'StartAnalyze': "¿Deseas iniciar el análisis? (s/n)",
    'AnalysisCancel': "Análisis cancelado por el usuario",
    'OnePartToken': "Primera parte del Token",
    'BannerColor': "Color del banner",
    'Expired': "Expirado",
    'FriendsBlock': "Introduce el amigo a bloquear",
    'FriendsList': "Lista de amigos",
    'Blocked': "Bloqueado",
    'BlockAll': "Bloquear a todos los amigos",
    'BlockOne': "Bloquear un solo amigo",
    'NoDm': "No se encontraron DMs",
    'Delete': "Eliminado",
    'Password': "Contraseña",
    'EncryptMetod': "Método de cifrado",
    'EncryptPassword': "Contraseña cifrada",
    'EncryptedPasswd': "Contraseña a cifrar",
    'PasswordCrackBrute': "Rompiendo contraseña por fuerza bruta.. (muy largo según el número de caracteres)",
    'PasswordCharacters': "Número máximo de caracteres de la contraseña",
    'Encryption': "El cifrado",
    'NotAccept': "no es aceptado por",
    'SavePassEncrypted': "¿Deseas guardar la contraseña cifrada en un archivo? (s/n)",
    'ConfirmPasswdSaved': "Contraseña cifrada en",
    'FileSizeReached': "Tamaño del archivo alcanzado",
    'OpenBrowser': "¿Abrir en el navegador? (s/n)",
    'OpenURL': "Abriendo la URL en tu navegador..."
	},
}
